config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    root "static_pages#home"
    devise_for :users
    resources :users, only: :show
    resources :jobs
    resources :curriculum_vitaes
    resources :curriculum_vitae_jobs, only: %i(new create)
    resources :organizations, only: %i(new create show)
    resources :tags, only: :show
    resources :follows
    resources :tags do
      member do
        post :follow, :unfollow
      end
    end
    resources :notifications, only: %i(index show)
    match "*unmatched_route", to: "application#route_not_found", via: :all
  end
end

app/models/job.rb
class Job < ApplicationRecord
  acts_as_taggable
  belongs_to :organization
  belongs_to :province
  belongs_to :career
  has_many :curriculum_vitae_jobs
  has_many :curriculum_vitaes, through: :curriculum_vitae_jobs,
    dependent: :destroy

  validates :title, presence: true, length: {maximum: Settings.max_length_title}
  validates :age_from, :age_to, presence: true, numericality: true,
    inclusion: {in: Settings.age_from..Settings.age_to}
  validates :skill, presence: true, length: {maximum: Settings.max_length_level}
  validates :salary, presence: true, numericality: true
  validates :work_address, presence: true,
    length: {maximum: Settings.max_length_address}
  validates :employment_type, presence: true,
    length: {maximum: Settings.max_length_level}
  validates :description, presence: true,
    length: {maximum: Settings.max_length_description}
  validates :experience, presence: true,
    length: {maximum: Settings.max_length_experience}
  validates_numericality_of :age_to, greater_than: :age_from
  validate :check_expried

  JOB_ATTRS = [:organization_id, :career_id, :province_id,
    :title, :age_from, :age_to, :salary, :work_address, :employment_type,
    :skill, :level, :experience, :description, :expiration_date,
    :tag_list].freeze

  scope :select_job, (lambda do
    select :id, :title, :salary, :experience, :expiration_date,
      :organization_id, :province_id, :created_at
  end)
  scope :order_job, ->{order created_at: :desc}
  scope :job_expired,
    ->{where(Job.arel_table[:expiration_date].gteq(Date.current))}

  after_create_commit :create_notification

  def check_expire? job
    job.expiration_date >= Date.current
  end

  private

  def create_notification
    self.tags.each do |tag_job|
      @tag = Tag.find_by id: tag_job.id
      @tag.followers.pluck(:id).each do |id|
        Notification.create user_id: id, target_type: Job.name,
          target_id: @tag.id, content: I18n.t(".noti_job") << @tag.name
      end
    end
  end

  def check_expried
    return unless expiration_date.presence
    return if expiration_date > Date.current
    errors.add :expiration_date, I18n.t(".expiration_date")
  end
end

app/models/supports/job.rb
class Supports::Job
  attr_reader :job, :user

  def initialize job, user
    @job = job
    @user = user
  end

  def career_options
    @career_options ||= Career.all.map{|p| [p.name, p.id]}
  end

  def province_options
    @province_options ||= Province.all.map{|p| [p.name, p.id]}
  end

  def organization_options
    @organization_options ||= @user.organizations.map{|p| [p.name, p.id]}
  end

  def cv_options
    @cv_options ||= @user.curriculum_vitaes.select(&:public?)
                         .map{|p| [p.industry, p.id]}
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: %i(new create)
  before_action :support, only: %i(new create index show)
  before_action :find_job, only: %i(show)

  def index
    @ransack = Job.select_job.job_expired.order_job.ransack params[:q]
    @jobs = @ransack.result.page(params[:page]).per Settings.per_sheet
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new job_params

    if @job.save
      flash[:success] = t ".success"
      redirect_to @job
    else
      flash[:danger] = t ".error"
      render :new
    end
  end

  def show
    return unless user_signed_in?
    @cv_job = @job.curriculum_vitae_jobs.build
  end

  private

  def find_job
    @job = Job.find_by id: params[:id]

    return if @job
    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  def support
    @support = Supports::Job.new @job, current_user
  end

  def job_params
    params.require(:job).permit Job::JOB_ATTRS
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def new_job? job
    date = Date.current - job.created_at.to_date
    return true if date < Settings.new_job
  end

  def user_organization? user, organization_id
    user.organization_users.exists? organization_id: organization_id
  end
end

app/views/jobs/_apply.html.erb
<%= form_with model: @cv_job, local: true do |f| %>
  <div><%= hidden_field_tag :job_id, @job.id %></div>
  <%= f.label :curriculum_vitae_id, t(".select") %>
  <%= f.select :curriculum_vitae_id, options_for_select(@support.cv_options),
    {include_blank: t(".choose")}, {class: "form-control"} %>

  <%= f.label :cv_upload, t(".upload") %>
  <%= f.file_field :cv_upload, accept: "application/pdf", class: "form-control" %>

  <%= f.submit t(".apply"), class: "btn btn-primary form-control" %>
<% end %>

app/views/jobs/_job.html.erb
<div class="col-sm-6 e-left">
  <div class="e-desc">
    <% if new_job? job %>
      <span class="float-right">
        <p class="flag-new text-uppercase"><%= t".new"%></p>
      </span>
      <h6 class="text-uppercase"><%= link_to job.title, job %></h6>
    <% else %>
      <h6 class="text-uppercase"><%= link_to job.title, job %></h6>
    <% end %>
    <% if job.tags.present? %>
      <ul class="tags">
        <li>
          <%= render "shared/show_tag", show_tag: job %>
        </li>
      </ul>
      <hr>
    <% else %>
      <hr>
    <% end %>
    <ul class="desc-list">
      <li>
        <span><%= t ".company" %></span>
        <%= job.organization.name %>
      </li>
      <% if user_signed_in? %>
        <li>
          <span><%= t ".salary" %></span>
          <%= number_to_currency job.salary %>
        </li>
      <% end %>
      <li>
        <span><%= t ".experience" %></span>
        <%= job.experience %>
      </li>
      <li>
        <span><%= t ".address" %></span>
        <%= job.province.name %>
      </li>
      <li>
        <span><%= t ".expiration" %></span>
        <%= l(job.expiration_date, format: :short) %>
      </li>
    </ul>
    <%= link_to t(".detail"), job, class: "btn wthree-bnr-btn text-capitalize" %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= render "shared/search" %>
    </div>
    <div class="col-lg-8">
      <div class="row">
        <% if @jobs.present? %>
          <%= render @jobs %>
        <% else %>
          <p><%= t ".not_found" %></p>
        <% end %>
      </div>
      <div class="row justify-content-center">
        <%= paginate @jobs, theme: "twitter-bootstrap-3" %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<% provide :title %>
<center><h1 class="text-uppercase mt-3"><%= t ".create_job" %></h1></center>

<div class="row justify-content-center mt-5">
  <div class="col-md-8">

    <%= form_with model: @job, local: true do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <div class="form-group">
        <%= f.label :organization_id %><br>
        <%= f.select :organization_id, options_for_select(@support.organization_options),
          {include_blank: t(".choose_organization")}, {class: "form-control"} %>
      </div>
      
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <%= f.label :career_id %><br>
          <%= f.select :career_id, options_for_select(@support.career_options),
            {include_blank: t(".choose_career")}, {class: "form-control"} %>
        </div>
        <div class="form-group col-md-4">
          <%= f.label :age_from %>
          <%= f.select :age_from,
            options_for_select(Settings.age_from..Settings.age_to),
            {include_blank: t(".age_from")}, {class: "form-control"} %>
        </div>
        <div class="form-group col-md-4">
          <%= f.label :age_to %>
          <%= f.select :age_to,
            options_for_select(Settings.age_from..Settings.age_to),
            {include_blank: t(".age_to")}, {class: "form-control"} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :skill %>
        <%= f.text_field :skill, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :level %>
        <%= f.text_field :level, class: "form-control" %>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :employment_type %>
          <%= f.text_field :employment_type, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :salary, t(".salary") %>
          <%= f.text_field :salary, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :work_address %>
          <%= f.text_field :work_address, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :province_id %><br>
          <%= f.select :province_id, options_for_select(@support.province_options),
            {include_blank: t(".choose_province")}, {class: "form-control"} %>
        </div>
      </div>
      
      <div class="form-group">
        <%= f.label :experience %>
        <%= f.text_area :experience, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :expiration_date %>
        <%= f.date_field :expiration_date, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :tag_list %><br/>
        <%= f.text_field :tag_list, class: "form-control" %>
      </div>

      <center><%= f.submit t(".create_job"), class: "btn btn-primary mb-3" %></center>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<% provide :title, @job.title %>
<div >
  <div class="container company mt-5">
    <div class="row">

      <div class="col-md-4 company_info mt-5">

        <%= image_tag "evolable-asia-logo.png", class: "mb-5" %><br>

        <i class="fa fa-home"></i>
        <p class="mt-5 "><%= t ".company" %>:&nbsp;</p>
        <p><%= link_to @job.organization.name,
            organization_path(@job.organization_id) %></p><br>
        <hr>

        <i class="fa fa-phone"></i>
        <p><%= t ".phone" %>:&nbsp;</p>
        <p><%= @job.organization.phone %></p><br>
        <hr>
        
        <i class="fa fa-envelope"></i>
        <p><%= t ".email" %>:&nbsp;</p>
        <p><%= @job.organization.email %></p><br>
        <hr>

        <i class="fa fa-globe"></i>
        <p><%= t ".website" %>:&nbsp;</p>
        <p><%= link_to @job.organization.website,
          @job.organization.website, target: "_blank" %></p><br>
        <hr>

        <i class="fa fa-map-marker"></i>
        <p><%= t ".address" %>:&nbsp;</p>
        <p><%= @job.organization.address %></p><br>
        <hr>
        
        <div class="info-icon">
          <i class="fa fa-facebook-square fa-2x facebook"></i>
          <i class="fa fa-google-plus-square fa-2x google"></i>
          <i class="fa fa-linkedin-square fa-2x linkedin"></i>
          <i class="fa fa-youtube-square fa-2x youtube"></i>
          <i class="fa fa-skype fa-2x skype"></i>
        </div>

        <ul class="tags mt-3">
          <li>
            <%= render "shared/show_tag", show_tag: @job %>
          </li>
        </ul>

        <% if user_signed_in? && user_organization?(current_user, @job.organization_id) %>
          <h3 class="mt-5 mb-3 cv_apply font-weight-bold text-uppercase">
            <%= t".cv_applied" %>&nbsp;(<%= @job.curriculum_vitaes.count %>)</h3>
          <%= render @job.curriculum_vitaes %>
        <%end %>
      </div>

      <div class="col-md-8 job_info">

        <% if new_job? @job %>
          <span class="flag float-right"><%= t ".new_job" %></span>
          <h3 class="text-uppercase font-weight-bold text-center mb-5">
            <%= @job.title %></h3>
        <% else %>
          <h3 class="text-uppercase font-weight-bold text-center mb-5">
            <%= @job.title %></h3>
        <% end %>

        <h5><%= t ".career" %></h5><hr>
        <p><%= @job.career.name %></p><br>

        <h5><%= t ".age" %></h5><hr>

        <p class="float-left"><%= t ".from" %>&nbsp;</p>
        <p class="float-left"><%= @job.age_from %>&nbsp;&nbsp;</p>

        <p class="float-left"><%= t ".to" %>&nbsp;</p>
        <p><%= @job.age_to %></p><br>

        <h5><%= t ".skill" %></h5><hr>
        <p><%= @job.skill %></p><br>

        <h5><%= t ".level" %></h5><hr>
        <p><%= @job.level %></p><br>

        <h5><%= t ".employment_type" %></h5><hr>
        <p><%= @job.employment_type %></p><br>

        <% if user_signed_in? %>
          <h5><%= t ".salary" %></h5><hr>
          <p><%= number_to_currency @job.salary %></p><br>
        <% end %>

        <h5><%= t ".work_address" %></h5><hr>
        <p><%= @job.work_address %></p><br>

        <h5><%= t ".experience" %></h5><hr>
        <p><%= @job.experience %></p><br>

        <h5><%= t ".description" %></h5><hr>
        <p class="text-justify"><%= @job.description %></p><br>

        <h5><%= t ".expiration_date" %></h5><hr>
        <p><%= l(@job.expiration_date, format: :short) %></p><br>

        <%= link_to t(".apply"), new_curriculum_vitae_job_path, class:
          "btn wthree-bnr-btn text-capitalize", data: {toggle: "modal",
            target: "#applyCV"} %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="applyCV" tabindex="-1" role="dialog"
  aria-labelledby="login_or_apply" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header bg-theme1">
        <h5 class="modal-title" id="login_or_apply">
          <% if !user_signed_in? %>
            <%= t ".r_login" %>
          <% else %>
            <%= t ".select_cv" %>
          <% end %>
        </h5>
        <button type="button" class="close" data-dismiss="modal"
          aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if !user_signed_in? %>
        <div class="button_cn">
          <%= link_to t(".signup"), "#", class: "btn btn-lg btn-warning" %>
          <%= link_to t(".login"), new_user_session_path, class: "btn btn-lg btn-warning" %>
        </div>
        <% else %>
          <%= render "apply" %>
        <% end %>
      </div>
    </div>
  </div>
</div>