config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    root "static_pages#home"
    devise_for :users
    resources :users, only: :show
    resources :jobs
    resources :curriculum_vitaes
    resources :curriculum_vitae_jobs, only: %i(new create)
    resources :organizations, only: %i(new create show)
    resources :tags, only: :show
    resources :follows
    resources :tags do
      member do
        post :follow, :unfollow
      end
    end
    resources :notifications, only: %i(index show)
    match "*unmatched_route", to: "application#route_not_found", via: :all
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error.contain" %> <%= pluralize object.errors.count, t("error.errors") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_search.html.erb
<div class="left_widget">
<%= search_form_for @ransack do |f| %>

  <h5 class="font-weight-bold text-center text-uppercase mb-3">
    <%= t ".search_job"%></h5>

    <%= f.text_field :title_cont, class: "form-control",
      placeholder: t(".title") %>

    <%= f.select :career_id_eq,
      options_for_select(@support.career_options),
      {include_blank: t(".choose_career")}, {class: "form-control"} %>

  <div class="form-row">
    <div class="col-md-6">
      <%= f.select :age_from_lteq,
        options_for_select(Settings.age_from..Settings.age_to),
        {include_blank: t(".age_from")}, {class: "form-control"} %>
    </div>
    <div class="col-md-6">
      <%= f.select :age_to_gteq,
        options_for_select(Settings.age_from..Settings.age_to),
        {include_blank: t(".age_to")}, {class: "form-control"} %>
    </div>
  </div>
  
    <%= f.text_field :skill_cont, class: "form-control",
      placeholder: t(".skill") %>

    <%= f.text_field :work_address_cont, class: "form-control",
      placeholder: t(".work_address") %>

    <button type="submit" 
      class="btn btn-w3ltd btn-block w-100 bg-theme font-weight-bold">
    <span class="fa fa-search"></span>
<% end %>
</div>

app/views/shared/_show_tag.html.erb
<li>
  <% show_tag.tag_list.each do |tag| %>
    <%= link_to tag, tag_path(tag) %>
  <% end %>
</li>