config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    root "static_pages#home"
    devise_for :users
    resources :users, only: :show
    resources :jobs
    resources :curriculum_vitaes
    resources :curriculum_vitae_jobs, only: %i(new create)
    resources :organizations, only: %i(new create show)
    resources :tags, only: :show
    resources :follows
    resources :tags do
      member do
        post :follow, :unfollow
      end
    end
    resources :notifications, only: %i(index show)
    match "*unmatched_route", to: "application#route_not_found", via: :all
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="py-sm-5 py-4 bg-theme footer">
  <div class="container">
    <div class="footer-top-w3ls">
      <h2><%= link_to t("base_title"), root_path, class: "navbar-brand" %></h2>
    </div>
    <div class="row pt-5">
      <div class="col-lg-6 footer_grid1">
        <h5><%= t ".address" %></h5>
        <div class="d-flex align-items-center">
          <p><i class="fa fa-home mr-3"></i> <%= t ".addr1" %></p>
        </div>
        <div class="d-flex mt-3 align-items-center">
          <p><i class="fa fa-home mr-3"></i> <%= t ".addr2" %></p>
        </div>
        <div class="d-flex mt-3 align-items-center">
          <p><i class="fa fa-home mr-3"></i> <%= t ".addr3" %></p>
        </div>
      </div>
      <div class="col-lg-6 mt-lg-0 mt-5">
        <h5><%= t ".contact" %></h5>
        <ul class="list-unstyled quick-links">
          <li>
            <i class="fa fa-envelope mr-3"></i> <%= t ".email" %></p>
          </li>
          <li>
            <i class="fa fa-phone mr-3"></i> <%= t ".phone" %></p>
          </li>
          <li>
            <i class="fa fa-print mr-3"></i> <%= t ".fax" %></p>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light p-0 navbar-static-top">
      <h1 class="title"><%= link_to t("base_title"), root_path, class: "navbar-brand" %></h1>
      <button class="navbar-toggler ml-lg-auto ml-sm-5 bg-light" type="button"
        data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="ml-lg-5 navbar-nav mr-lg-auto">
          <li class="nav-item mr-lg-4 mt-lg-0 mt-sm-4 mt-3">
            <%= link_to t(".createCV"), new_curriculum_vitae_path %>
          </li>
          <% if user_signed_in? && current_user.organization_users.present? %>
            <li class="nav-item  mr-lg-4 mt-lg-0 mt-sm-4 mt-3">
              <%= link_to t(".createJob"), new_job_path %>
            </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <li class="dropdown dropdown-animated scale-left">
            <a href="#" data-toggle="dropdown">
              <i class="fa fa-bell" aria-hidden="true"></i>
            </a>
            <ul class="dropdown-menu dropdown-lg p-v-0 notifications">
              <li class="p-v-15 p-h-20 border bottom text-dark">
                <h5 class="m-b-0">
                  <i class="fa fa-bell-o" aria-hidden="true"></i>
                  <span><%= t ".noti" %></span>
                </h5>
              </li>
              <li>
                <ul class="list-media overflow-y-auto relative scrollable">
                  <% if show_notifications.present? %>
                    <%= render @notifications %>
                  <% else %>
                    <li class="list-item border bottom">
                      <div class="info">
                        <%= t ".no_noti" %>
                    </div>
                    </li>
                  <% end %>
                </ul>
              </li>
              <li class="p-v-15 p-h-20 text-center">
                <span>
                  <%= link_to t(".show_all"), notifications_path, class: "text-gray" %>
                </span>
              </li>
            </ul>
          </li>
          <%= link_to current_user.name, current_user,
            class: "btn w3ls-btn text-uppercase font-weight-bold d-block" %>
          <li class="dropdown nav-item mr-lg-3 mt-lg-0 mt-sm-4 mt-3 list-group float-right">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".organization"), new_organization_path %></li>
              <li><%= link_to t(".logout"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to t(".signup"), "#",
            class: "btn w3ls-btn text-uppercase font-weight-bold d-block" %>
          <%= link_to t(".login"), new_user_session_path,
            class: "btn w3ls-btn btn-2 ml-lg-1 text-uppercase font-weight-bold d-block" %>
        <% end %>
      </div>
    </nav>
  </div>
</header>
<div class="d-flex banner-w3pvt-bg1 common-bg header">
  <div class="d-flex mx-auto align-items-center justify-content-center flex-column">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container home">
      <% if notice %>
        <p class="alert alert-success flash"><%= notice %></p>
      <% elsif alert %>
        <p class="alert alert-danger flash"><%= alert %></p>
      <% else %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %> flash"><%= message %></div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= wicked_pdf_stylesheet_link_tag "pdfs" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>